# Generated by Django 5.0.3 on 2024-05-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='deadline',
            field=models.DateField(),
        ),
    ]
