# Generated by Django 5.0.3 on 2024-05-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_challenge_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
