# Generated by Django 5.0.3 on 2024-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_pushnotificationticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_season', models.BooleanField(default=True)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('season_total_workouts', models.IntegerField()),
                ('month_goal', models.IntegerField()),
                ('week_goal', models.IntegerField()),
            ],
        ),
    ]
